---
- name: Configure Attacker machines
  hosts: all
  become: true
  tasks:
  #Network configuration ( static ip)
    - name: Add an Ethernet connection with static IP configuration
      community.general.nmcli:
        conn_name: LabEth
        ifname: eth1
        type: ethernet
        ip4: 10.0.3.2/24
        gw4: 10.0.3.1
        route_metric4: 50
        state: present
        conn_reload: true
      notify: Restart Networking

    - name: Permanently ignore NAT routes on eth0
      ansible.builtin.shell: |
        nmcli device modify eth0 ipv4.ignore-auto-routes yes
        while ip route del default via 10.0.2.2 dev eth0; do :; done
      ignore_errors: true

    - name: Prevent eth0 from asserting default route on resume
      community.general.nmcli:
        conn_name: "Wired connection 1"
        type: ethernet
        ifname: eth0
        never_default4: true
        state: present

  handlers:
    - name: Restart Networking
      service:
        name: networking
        state: restarted



