---
- name: Configure web server
  hosts: all
  become: true
  tasks:

    - name: static IP netplan
      copy:
        dest: /etc/netplan/99-netbed-config.yaml
        mode: '0600'
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              enp0s8:
                dhcp4: no
                addresses:
                  - 10.0.4.2/24

                routes:
                  - to: default
                    via: 10.0.4.1
                    metric: 50
                
                nameservers:
                  addresses: [8.8.8.8, 8.8.4.4]
      notify: apply Netplan


    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Apache web server
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Force Netplan to apply now
      ansible.builtin.meta: flush_handlers

    - name: Strip all instances of NAT default gateway
      ansible.builtin.shell: |
        while ip route del default via 10.0.2.2 dev enp0s3; do :; done
      ignore_errors: true


  handlers:
    - name: apply Netplan
      command: netplan apply